- name: Deploy simple dockerized python (uvicorn) webapp un Ubuntu server
  hosts: myhosts
  become: true
  vars:
    git_repo_url: "https://github.com/nestef23/python_experiments.git"
    git_clone_dir: "/git"
    
  tasks:
    - name: Ensure Git is installed
      package:
        name: git
        state: present

    - name: Create target directory
      file:
        path: "{{ git_clone_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Clone the Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_clone_dir }}"
        version: HEAD
        force: no      #Do NOT overwrite local changes
        update: yes

# Not needed for docker. Docker modifies iptables directly to expose ports, and UFW doesn’t see those connections.
#    - name: Check if ufw is available
#      ansible.builtin.shell: command -v ufw
#      register: ufw_path
#      failed_when: false
#      changed_when: false
      
#    - name: Check if UFW rule for 8000/tcp already exists 
#      ansible.builtin.command: ufw status numbered
#      register: ufw_status
#      changed_when: false
#      failed_when: false

#    - name: Open port in ufw if not already open 
#      ansible.builtin.command: "ufw allow 8000/tcp"
#      when: "'8000/tcp' not in ufw_status.stdout"
     
    - name: Install prerequisite packages for Docker - Ubuntu
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Engine packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      
    - name: Launch the FastAPI app with Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ git_clone_dir }}/simple-uvicorn-docker/"
        state: present
        build: always         # Always rebuild the image
        recreate: auto       # Only recreate containers if needed
